### PR TITLE
🐛(eleventy-plugin-local-respimg) Respect `loading` attr set on <img> tags

### LINKED ISSUE #31: [eleventy-plugin-local-respimg] Feature request: Allow overriding loading="lazy"
Version: 0.3.1

Using `lazy: true` in the config adds loading="lazy" to all img tags. I would like to use this, but also be able to explicitly set loading="eager" on some images, which are displayed above the fold. However, loading="eager" always gets overwritten if it is set.
Individual overrides per image is already possible when specifying the "sizes" attribute.

### PR DESCRIPTION
**Pull request by saneef**
- Also updates tests

Closes #31

### CODE REVIEW

**Comment by saneef** [comment]
👋 @Snugug Could you check this PR and make a new release if things are okay?

**Comment by Snugug** [comment]
Sorry, between the holidays and personal stuff the past couple weeks got away from me. Will look at everything Monday

**Comment by Snugug** [comment]
Sorry for the delay on this! Was launching http://chromeos.dev/ which ate my time on this. Back on this, now, though.

**Comment by saneef** [comment]
Thanks @Snugug for merging. It would be great if you could publish a new version of this plugin.

**Comment by saneef** [comment]
Hey @Snugug nudging to make a release. 🥺  The last release on [NPM](https://www.npmjs.com/package/eleventy-plugin-local-respimg) was in June.

**Pull request merged**
