### PR TITLE
🐛 (eleventy-plugin-safe-external-links) Fixes failure when permalink: false

### PR DESCRIPTION
**Pull request by saneef**

### CODE REVIEW

**Comment by saneef** [comment]
@Snugug Is it possible to know whether these changes have been released?

**Comment by Snugug** [comment]
I'll do it later today

**Comment by saneef** [comment]
@Snugug Could you make a release? Sorry to trouble you. No other way to use these fixes because of monorepo.

**Comment by Snugug** [comment]
Sorry sorry, had two crazy days. Rolling now.

**Comment by saneef** [comment]
No worries. Thanks a lot :)

**Pull request merged**
